name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version number
        required: true

jobs:
  release:
    name: Publish new version
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PAT_TOKEN }}

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Get Swift version
      id: swift-version
      run: echo "::set-output name=version::$(swift -version | shasum | cut -d' ' -f 1)"
      shell: bash
    - name: Cache SwiftPM dependencies
      uses: actions/cache@v2
      with:
        path: .build
        key: generated-${{ runner.os }}-spm-${{ steps.swift-version.outputs.version }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          generated-${{ runner.os }}-spm-${{ steps.swift-version.outputs.version }}-
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node modules
      run: npm ci
      working-directory: relay-compiler-language-swift

    - name: Update language plugin package version
      run: |
        sed -i '' -e 's/"version": ".*",$/"version": "${{ github.event.inputs.version }}",/' package.json
      working-directory: relay-compiler-language-swift

    - name: Commit version bump
      run: git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -am "Update version to ${{ github.event.inputs.version }}"

    - name: Tag commit
      run: git tag "${{ github.event.inputs.version }}"

    - name: Publish package
      run: npm publish
      working-directory: relay-compiler-language-swift
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    - name: Push commit and tags
      run: git push --tags origin main
